version: "3.9"

services:
  openhands:
    image: docker.all-hands.dev/all-hands-ai/openhands:latest
    environment:
      SANDBOX_RUNTIME_CONTAINER_IMAGE: docker.all-hands.dev/all-hands-ai/runtime:latest
      SANDBOX_VOLUMES: ${CODE_PATH:-$PWD}:/workspace:rw
      SANDBOX_USER_ID: ${UID:-1000}
      # Uncomment if Linux networking issues persist:
      # SANDBOX_USE_HOST_NETWORK: "true"
      # DOCKER_HOST_ADDR: "127.0.0.1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    # As a last resort on Linux (can affect UI workspace view):
    # network_mode: "host"
