"""Idea generation data model"""

from sqlalchemy import Column, String, Text, Float, DateTime, JSON
from sqlalchemy.sql import func
from .base import Base


class Idea(Base):
    """
    Research idea model for AI-generated research ideas.

    Stores ideas generated by the system with scoring and metadata.
    """
    __tablename__ = "ideas"

    # Primary key
    id = Column(String(64), primary_key=True)

    # Foreign keys
    session_id = Column(String(64), nullable=False, index=True)

    # Content
    title = Column(String(512), nullable=False)
    description = Column(Text, nullable=False)
    topic = Column(String(256), nullable=False)

    # Scores (0.0 - 1.0)
    novelty_score = Column(Float, nullable=True)
    feasibility_score = Column(Float, nullable=True)
    impact_score = Column(Float, nullable=True)

    # Metadata
    tags = Column(JSON, nullable=True)  # Array of strings
    related_work = Column(JSON, nullable=True)  # Array of strings
    potential_challenges = Column(JSON, nullable=True)  # Array of strings

    # Timestamps
    created_at = Column(DateTime, default=func.now())

    # Status
    status = Column(String(32), default="generated")  # generated, selected, tested

    def __repr__(self):
        return f"<Idea {self.id}: {self.title[:50]}>"

    def to_dict(self):
        """Convert to dictionary for API responses"""
        return {
            'id': self.id,
            'session_id': self.session_id,
            'title': self.title,
            'description': self.description,
            'topic': self.topic,
            'scores': {
                'novelty': self.novelty_score,
                'feasibility': self.feasibility_score,
                'impact': self.impact_score,
            },
            'tags': self.tags or [],
            'related_work': self.related_work or [],
            'potential_challenges': self.potential_challenges or [],
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'status': self.status,
        }
